export const allEnrollments = [
  {
    id: 1,
    desc: "People Management",
    course: "MANAGEMENT",
    img: "",
    allowedRoles: ["learner", "student"],
  },
  {
    id: 2,
    desc: "Advance Rush",
    course: "BLOCHCHAIN",
    img: "",
    allowedRoles: ["learner", "student"],
  },
  {
    id: 3,
    desc: "Robotics & Machine Learning",
    course: "ARTICIAL INTELLIGENCE",
    img: "",
    allowedRoles: ["learner", "student"],
  },
  {
    id: 4,
    desc: "Intro to Python",
    course: "Coding",
    img: "",
    allowedRoles: ["learner", "student"],
  },
  {
    id: 5,
    desc: "Intro to Javascript",
    course: "Coding",
    img: "",
    allowedRoles: ["learner", "student"],
  },
  {
    id: 6,
    desc: "Ethical Hacking",
    course: "Coding",
    img: "",
  },
  {
    id: 7,
    desc: "Intro to C++",
    course: "Coding",
    img: "",
  },
  {
    id: 8,
    desc: "Intro to Programming",
    course: "Language",
    img: "",
    allowedRoles: ["learner", "student"],
  },
  {
    id: 9,
    desc: "Intro to C",
    course: "Coding",
    img: "",
    allowedRoles: ["learner", "student"],
  },
  {
    id: 10,
    course: "Javascript",
    img: "",
    desc: "Beginner’s Guide to becoming  a      professional frontend developer",
  },
  {
    id: 11,
    course: "React JS",
    img: "",
    desc: "Beginner’s Guide to becoming       a       professional frontend developer",
  },
  {
    id: 12,
    course: "Python",
    img: "",
    desc: "Beginner’s Guide to becoming      a       professional frontend developer",
  },
  {
    id: 13,
    desc: "Beginner’s Guide to becoming       a       professional Software Engineer.",
    img: "",
    course: "Software Enginering",
  },
];
